"""Add actual_runtime and reward_score to RoutingHistory

Revision ID: 7d137dec7e12
Revises: c1a5a2758ab8
Create Date: 2026-06-19 19:09:18.520594

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d137dec7e12"
down_revision: str | Sequence[str] | None = "c1a5a2758ab8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("routing_history", sa.Column("actual_runtime", sa.Float(), nullable=True))
    op.add_column("routing_history", sa.Column("reward_score", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("routing_history", "reward_score")
    op.drop_column("routing_history", "actual_runtime")
    # ### end Alembic commands ###
