"""Add RoutingHistory model

Revision ID: c1a5a2758ab8
Revises: 18536087d77b
Create Date: 2026-06-19 18:53:08.907872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a5a2758ab8'
down_revision: Union[str, Sequence[str], None] = '18536087d77b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routing_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_hash', sa.String(), nullable=False),
    sa.Column('strategy_selected', sa.String(), nullable=False),
    sa.Column('exploration_mode', sa.Boolean(), nullable=False),
    sa.Column('expected_cost', sa.Float(), nullable=True),
    sa.Column('expected_accuracy', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('actual_accuracy', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_history_strategy_selected'), 'routing_history', ['strategy_selected'], unique=False)
    op.create_index(op.f('ix_routing_history_task_hash'), 'routing_history', ['task_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routing_history_task_hash'), table_name='routing_history')
    op.drop_index(op.f('ix_routing_history_strategy_selected'), table_name='routing_history')
    op.drop_table('routing_history')
    # ### end Alembic commands ###
