"""Add StrategyOutcome model

Revision ID: d82db60389dc
Revises: 7d137dec7e12
Create Date: 2026-06-19 19:10:57.343708

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd82db60389dc'
down_revision: str | Sequence[str] | None = '7d137dec7e12'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_outcomes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_hash', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('avg_accuracy', sa.Float(), nullable=True),
    sa.Column('avg_cost', sa.Float(), nullable=True),
    sa.Column('avg_runtime', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_outcomes_strategy'), 'strategy_outcomes', ['strategy'], unique=False)
    op.create_index(op.f('ix_strategy_outcomes_task_hash'), 'strategy_outcomes', ['task_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_outcomes_task_hash'), table_name='strategy_outcomes')
    op.drop_index(op.f('ix_strategy_outcomes_strategy'), table_name='strategy_outcomes')
    op.drop_table('strategy_outcomes')
    # ### end Alembic commands ###
